/*
 * Expeneses API
 *
 * API providing data for expeneses new project|
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tomerk@kkl.org.il
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using amitalTest.Attributes;
using amitalTest.Models;
using amitalTest.Repositories;

namespace amitalTest.Controllers
{
    
    /// <summary>
    /// 
    /// </summary>
    [ApiController] 
    public class UsersApiController : ControllerBase
    {
        private readonly IUsersRepository _repository;

        public UsersApiController(IUsersRepository repository)
        {
            _repository = repository;
        }
    
        /// <summary>
        /// Get list of users
        /// </summary>
        /// <response code="200">OK</response>
        /// <response code="400">If any data is incorrect</response>
        /// <response code="500">If any server Error</response>
        [HttpGet]
        [Route("/users")]
        [ValidateModelState]
        [SwaggerOperation("GetAllUsers")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Users>), description: "OK")]
        public virtual async Task<IActionResult> GetAllUsers()
        {
            return Ok(await _repository.GetAllUsers());
        }
    }
}
